name = "Stochastics"
uuid = "88c8ce17-7ba1-4c24-b359-c3804bac64b9"
authors = ["persson-io <rasmus@persson.io> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
